server:
  port: 8089

spring:
  application:
    name: content-queue-service
  profiles:
    active: @spring.profiles.active@
  config:
    import: optional:nacos:@common.dataId@
  cloud:
    nacos:
      discovery:
        server-addr: @nacos.server-addr@
        namespace: @nacos.namespace@
      config:
        server-addr: @nacos.server-addr@
        namespace: @nacos.namespace@
        file-extension: yml
        import-check:
          enabled: false
        shared-configs:
          - dataId: @common.dataId@
            group: DEFAULT_GROUP
            refresh: true

knife4j:
  enable: true
  openapi:
    title: 内容分享平台消息队列服务 API
    description: 内容分享平台消息队列服务接口文档
    version: 1.0.0
    group:
      default:
        api-rule:
          include-path-patterns: 
            - /api/**
